export const router = {
    home: '/',
    login: '/login',
    register: '/register',
    profile: '/profile',
    createProduct: '/add-product',
    editProfile: '/profile/edit',
    allProduct: '/products',
    productDetail: '/product/:id',
    listUser: '/admin/user',
    createUser: '/admin/create-user',
    updateUserAdmin: '/admin/edit-user/:id',
    editProduct: '/product/:id',
    createShipment: 'create-shipment',
    listShipment: '/admin/shipment',
    updateShipment: '/update-shipment/:id',
    driverUserId: '/drive-shipment',
    driverUpdate: '/drive-detail-shipment/:id',
};
